advcbv/advcbv/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.IndexView.as_view()),
    path("basic_app/", include("basic_app.urls")),
]

advcbv/basic_app/urls.py
from django.urls import path
from basic_app import views

# TEMPLATE TAGGING
app_name = "basic_app"

urlpatterns = [
    path("", views.SchoolListView.as_view(), name="list"),
    path("<int:pk>/", views.SchoolDetailView.as_view(), name="detail"),
    path("create/", views.SchoolCreateView.as_view(), name="create"),
    path("update/<int:pk>/", views.SchoolUpdateView.as_view(), name="update"),
    path("delete/<int:pk>/", views.SchoolDeleteView.as_view(), name="delete"),
]

advcbv/basic_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("basic_app:detail", kwargs={"pk": self.pk})
    

class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School, related_name="students", on_delete=models.CASCADE)

    def __str__(self):
        return self.name

advcbv/basic_app/views.py
from django.shortcuts import render
from django.views.generic import View, TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from . import models
from django.urls import reverse_lazy

# Create your views here.
class IndexView(TemplateView):
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["injectme"] = "BASIC INJECTION"
        return context

class SchoolListView(ListView):
    context_object_name = "schools"
    model = models.School

class SchoolDetailView(DetailView):
    context_object_name = "school_detail"
    model = models.School
    template_name = "basic_app/school_detail.html"

class SchoolCreateView(CreateView):
    fields = ("name", "principal", "location")
    model = models.School

class SchoolUpdateView(UpdateView):
    fields = ("name", "principal")
    model = models.School

class SchoolDeleteView(DeleteView):
    context_object_name = "school"
    model = models.School
    success_url = reverse_lazy("basic_app:list")

advcbv/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html>
<head>
    <title>My Simple HTML Page</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
</head>
<body>
    <nav
        class="navbar navbar-inverse navbar-fixed-top"
        role="navigation"
    >
        <ul class="nav navbar-nav">
            <li><a class="navbar-brand" href="{% url 'basic_app:list' %}">Schools</a></li>
            <li><a class="navbar-link"href="{% url 'admin:index' %}">Admin</a></li>
            <li><a class="navbar-link" href="#"></a></li>
        </ul>

    </nav>

    {% block body_block%}
    {% endblock %}
</body>
</html>

advcbv/basic_app/templates/basic_app/school_confirm_delete.html
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %}
    <div class="jumbotron">
    <h1>Delete {{school.name}}</h1>
    <form method="POST">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Confirm Delete">
        <a href="{% url 'basic_app:detail' pk=school.pk %}" class="btn btn-primary">Cancel</a>
    </form>
    </div>

{% endblock %}

advcbv/basic_app/templates/basic_app/school_detail.html
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %}
    <div class="jumbotron">
    <h1>Welcome to the School Detail Page</h1>
    <h2>School Details:</h2>
    <p>School Name: {{ school_detail.name }}</p>
    <p>School Principal: {{ school_detail.principal }}</p>
    <p>School Location: {{ school_detail.location }}</p>
    <h3>Students:</h3>
    <ul>
        {% for student in school_detail.students.all %}
            <li>{{ student.name }}</li>
        {% endfor %}
    </ul>
    </div>
    <div class="container">
        <a class="btn btn-warning" href="{% url 'basic_app:update' pk=school_detail.pk %}">Update School</a>
        <a class="btn btn-danger" href="{% url 'basic_app:delete' pk=school_detail.pk %}">Delete School</a>
        <a class="btn btn-primary" href="{% url 'basic_app:list' %}">Back to School List</a>
    </div>

{% endblock %}

advcbv/basic_app/templates/basic_app/school_form.html
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %}
    <div class="jumbotron">
    <h1>
        {% if not form.instance.pk %}
        Create School
        {% else %}
        Update School
        {% endif %}
    </h1>
    <form method="POST" class="form">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary" value="Submit">
    </form>
    </div>
{% endblock %}

advcbv/basic_app/templates/basic_app/school_list.html
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %}
    <div class="jumbotron">
    <h1>Welcome to a list of all the schools</h1>
    <ol>
        {% for school in schools %}
            <h2><li><a href="{{ school.id }}">{{ school.name }}</a></li></h2>
        {% endfor %}
    </ol>
    </div>
{% endblock %}

advcbv/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>My Simple HTML Page</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
</head>
<body>
    <nav
        class="navbar navbar-inverse navbar-fixed-top"
        role="navigation"
    >
        <ul class="nav navbar-nav">
            <li><a class="navbar-brand" href="{% url 'basic_app:list' %}">Schools</a></li>
            <li><a class="navbar-link"href="{% url 'admin:index' %}">Admin</a></li>
            <li><a class="navbar-link" href="#"></a></li>
        </ul>

    </nav>

    {% block body_block%}
    {% endblock %}
</body>
</html>

advcbv/templates/index.html
{% extends "base.html" %}
{% block body_block %}
    <div class="jumbotron">
        <h1>Home Page</h1>
        <h2> Injected Content: {{ injectme }}</h2>
    </div>
{% endblock %}