first_project/first_app/urls.py
from django.urls import path
from first_app import views

app_name = 'first_app'

urlpatterns = [
    path("",views.index, name='AI Simplified'),
    path("register/",views.register, name="register"),
    path("user_login/",views.user_login, name="user_login"),
]

first_project/first_project/urls.py
from django.contrib import admin
from django.urls import path
from first_app import views

urlpatterns = [
    path("",views.index, name='AI Simplified'),
    path("admin/", admin.site.urls),
]

first_project/first_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    #additional
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self) -> str:
        return self.user.username


class Topic(models.Model):
    top_name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.top_name

class Webpage(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    name = models.CharField(max_length=255, unique=True)
    url = models.URLField(unique=True)

    def __str__ (self):
        return self.name

class AccessRecord(models.Model):
    name = models.ForeignKey(Webpage, on_delete=models.CASCADE)
    date = models.DateField()

    def __str__(self):
        return (self.date)

first_project/first_app/forms.py
from django import forms
from django.contrib.auth.models import User
from first_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ("username", "email", "password")

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ("portfolio_site", "profile_pic")

first_project/first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from first_app.models import Topic, Webpage, AccessRecord
from first_app.forms import UserForm, UserProfileInfoForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    webpage_list = AccessRecord.objects.order_by('date')
    date_dict = {'access_records':webpage_list}
    return render(request, 'first_app/index.html', context=date_dict)

def register(request):
    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        
        if user_form.is_valid() and profile_form.is_valid():
            
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            
            profile = profile_form.save(commit=False)
            profile.user = user
            
            if 'profile_pic' in request.FILES:
                print('found it')
                profile.profile_pic = request.FILES['profile_pic']
                
            profile.save()
            
            registered = True
            
        else:
            print(user_form.errors, profile_form.errors)
    
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
        
    return render(request, 'first_app/registration.html',
                  {'user_form':user_form,
                   'profile_form':profile_form,
                   'registered':registered})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def special(request):
    return HttpResponse("You are logged in, Nice!")

def user_login(request):
    
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        user = authenticate(username=username, password=password)
        
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        
        else:
            print("Someone tried to login and failed")
            print("Username: {} and password {}".format(username,password))
            return HttpResponse("invalid login details supplied")
        
    else:
        return render(request, 'first_app/login.html', {})

first_project/templates/first_app/base.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
	<nav class='navbar navbar-default navbard-static-top'>
        <div class='container'>
            <ul class='nav navbar-nav'>
                <li><a class='navbar-brand' href='{url "index" }'>Home</a></li>
                <li><a class='navbar-link'href='{%url "admin:index" %}'>Admin</a></li>
                <li><a class='navbar-link'href='{% url "first_app:register" %}'>Register</a></li>
                {% if user.is_authenticated%}
                <li><a class='navbar-link'href='{% url "logout" %}'>Logout</a></li>
                {% else %}
                <li><a class='navbar-link'href='{% url "first_app:user_login" %}'>Login</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <div class='container'>
        {% block body_block %}
        {% endblock %}
    </div>
</body>
</html>

first_project/templates/first_app/index.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <title>First App</title>
    <link rel="stylesheet" href="{% static "css/style.css" %}"/>
  </head>
  <body>
    <h1>Welcome to my page!</h1>
    {{ insert_me }}
    <p>This is a simple HTML page.</p>
    <img src="{% static "images/3.png " %}" alt=""/>
    <div class="djangotwo">
      {% if access_records %}
      <table>
        <thead>
          <th>Site Name</th>
          <th>Date Accessed</th>
        </thead>
        {% for acc in access_records %}
        <tr>
          <td>{{acc.name}}</td>
          <td>{{acc.date}}</td>
        </tr>
        {% endfor %}
      </table>
      {% else %}
       <p>No access to records</p>
      {% endif %}
    </div>
  </body>
</html>

first_project/templates/first_app/login.html
{% extends 'first_app/base.html' %}
{% block body_block %}
    <h1>Please Login</h1>
    <form action="{url 'first_app:user_login'} %" method="post">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter Username" required>

        <label for="password">Password:</label>
        <input type="password" name="password" placeholder="Enter Password" required> 

        <input type="submit" name="submit" value="Login">
    </form>
{% endblock %}

first_project/templates/first_app/registration.html
{% extends 'first_app/base.html' %}
{% load static %}

{% block body_block %}

<div class="jumbotron">
    {% if registered %}
    <h1> Thank you for registering! </h1>
    {% else %}
    <h1> Register here! </h1>
    <h3> Fill out the form below to register! </h3>
    <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" name="submit" value="Register" class="btn btn-primary">
    <form>
    {% endif %}
</div>

{% endblock %}